language: node_js
node_js:
  - lts/*
cache: yarn
install: yarn
script: yarn test
deploy:
  provider: npm
  email: mariosant@sent.com
  skip_cleanup: true
  api_key:
    secure: VeY64DLSJ6qXGhIJkoGVa09LJGHc15BuJE7i6vCxkBbBKAKsdufsIz71fxBUZ+fhEbwN07d0Q5tVEkecrjgSh6o/uOjEVWJQKXXMBp1u3Gse+mxpueyt1te4WJt97gQk3QgDnRV6Zo5hL4XuIExX19XTVoMQAdojrykvHkvxutXspPg1TE2aiA/YsLH8T8Rq+rQc53y9wN6g+q/Y3vhafikep7IBMH6iZ3FEb4F4G3Gp9gBnBDh1z3YPSPwD2q6CAZHepCBNcDuGC/EAX8CSjqFNlngd1JRyFhrkSkqwaKnvjfl9Tg09SQGN5IeWrTFV57+l/SKB53r7HbPYkc90KhZcG3KP2h4pH8qcv9TG3m3nkLKHDMTAlXAp8aafr4OCTV3GTJ0Z04BbqdtnRKEzPMl4Ze3LHVbL+7RnEh1OkIWcQRQhgEJr94BF/IGfx3aytkNoN5VVt4MtpUZkxSLBaI7XzQx9X/op6enywZLuzfni27Pk2U7PGQIJxlwcP4SabVsJ/wJ+iSbmG81oz1T3JdLm9V2fIZERtIHfdQ3RSCCfMhyzTPMzQeTZr/KX6pX1XVnpphbQcNlzw9ij0BodY4PSImPU0e5GlMUMKExBON0cYglHnzL3c8EsaKGkM2+zI18OKr3XYp48TsVhcInuhoiCC4SP8fRRhlblCHkGhQA=
  on:
    tags: true
    repo: mariosant/react-sweet-scroll
